In [37]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
x = np.array(["Hello" , "World", "Fun", "Fair"])

In [3]:
print(x)

['Hello' 'World' 'Fun' 'Fair']


In [4]:
le = LabelEncoder()

In [5]:
X = le.fit(x)

In [6]:
print(X)

LabelEncoder()


In [7]:
X = le.transform(x)

In [8]:
X

array([2, 3, 1, 0])

In [9]:
ethnicity_for_encoding = ['White-European', 'Middle Eastern', 'Pasifika', 'Black', 'Hispanic','Asian', 'Turkish', 'South Asian','Latino','Others']

In [10]:
le.fit(ethnicity_for_encoding)

LabelEncoder()

In [11]:
oo = le.transform(ethnicity_for_encoding)

In [12]:
print(oo)

[9 4 6 1 2 0 8 7 3 5]


In [13]:
questionnaires = {
        "Avoids eye contact with others." : {"Yes" : 1, "No" : 0},
        "Has trouble understanding other people’s feelings." : {"Yes" : 1, "No" : 0},
        "Prefers to be alone rather than with others." : {"Yes" : 1, "No" : 0},
        "Has unusually intense interests." : {"Yes" : 1, "No" : 0},
        "Has difficulty understanding the back-and-forth flow of normal conversation.." : {"Yes" : 1, "No" : 0},
        "Responds inappropriately to other's attempts at social interaction (e.g., doesn’t answer or walks away)." : {"Yes" : 1, "No" : 0},
        "Shows little interest in playing with other children." : {"Yes" : 1, "No" : 0},
        "Overreacts to minor changes in routine or environment." : {"Yes" : 1, "No" : 0},
        "Focuses intensely on particular topics or interests, often at the exclusion of everything else." : {"Yes" : 1, "No" : 0},
        "Uses unusual tone of voice, pitch, or rhythm when speaking." : {"Yes" : 1, "No" : 0}
    }

questions_list = []
for questions, ans in questionnaires.items():
    answer = ans
    questions_list.append(answer)

print(questions_list)

# for question, ans in questionnaires.items():
#     questions_list.append(ans)  # append the value directly

# print(questions_list)


[{'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}, {'Yes': 1, 'No': 0}]


In [14]:
wer = {'southeast' : 0, 'southwest' : 1, 'northwest' : 3, 'northeast': 2}

In [15]:
wer['southeast']

0

In [16]:
# A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,age,gender,ethnicity,jaundice,austim,contry_of_res,used_app_before,result,relation

In [18]:


le.fit(ethnicityDict)



LabelEncoder()

In [20]:
X = le.transform(ethnicityDict)

In [21]:
print(X)

[9 4 6 1 2 0 8 7 3 5]


In [23]:
ethnicity_dict = {'White-European' : 
    'White-European', 'Middle Eastern' : 'Middle Eastern', 'Pasifika' : 'Pasifika', 'Black' : 'Black', 'Hispanic' : 'Hispanic', 'Asian' : 'Asian', 'Turkish' : 'Turkish', 'South Asian' : 'South Asian', 'Latino' : 'Latino', 'Others' : 'Others'}

In [25]:
X = list(ethnicity_dict.values())

In [26]:
X

['White-European',
 'Middle Eastern',
 'Pasifika',
 'Black',
 'Hispanic',
 'Asian',
 'Turkish',
 'South Asian',
 'Latino',
 'Others']

In [27]:
le.fit(X)

LabelEncoder()

In [30]:
Y =le.transform(X)

In [31]:
print(Y)

[9 4 6 1 2 0 8 7 3 5]


In [32]:
country_of_res = ['Austria', 'India', 'United States', 'South Africa', 'Jordan','United Kingdom', 'Brazil', 'New Zealand', 'Canada', 'Kazakhstan','United Arab Emirates', 'Australia', 'Ukraine', 'Iraq', 'France','Malaysia', 'Vietnam', 'Egypt', 'Netherlands', 'Afghanistan','Oman', 'Italy', 'Bahamas', 'Saudi Arabia', 'Ireland', 'Aruba','Sri Lanka', 'Russia', 'Bolivia', 'Azerbaijan', 'Armenia','Serbia', 'Ethiopia', 'Sweden', 'Iceland', 'China', 'Angola','Germany', 'Spain', 'Tonga', 'Pakistan', 'Iran', 'Argentina','Japan', 'Mexico', 'Nicaragua', 'Sierra Leone', 'Czech Republic','Niger', 'Romania', 'Cyprus', 'Belgium', 'Burundi', 'Bangladesh']


In [33]:
len(country_of_res)

54

In [35]:
data = {
    "row1": {"fruit": "apple", "color": "red"},
    "row2": {"fruit": "banana", "color": "yellow"},
    "row3": {"fruit": "grape", "color": "green"}
}

In [38]:
df = pd.DataFrame.from_dict(data, orient="index")
print("Original DataFrame:\n", df)


Original DataFrame:
        fruit   color
row1   apple     red
row2  banana  yellow
row3   grape   green


In [40]:
questionnaires = [
    "Avoids eye contact with others.",
    "Has trouble understanding other people’s feelings.",
    "Prefers to be alone rather than with others.",
    "Has unusually intense interests.",
    "Has difficulty understanding the back-and-forth flow of normal conversation..",
    "Responds inappropriately to other's attempts at social interaction (e.g., doesn’t answer or walks away)." ,
    "Shows little interest in playing with other children.",
    "Overreacts to minor changes in routine or environment.",
    "Focuses intensely on particular topics or interests, often at the exclusion of everything else.",
    "Uses unusual tone of voice, pitch, or rhythm when speaking."
]

In [41]:
yes_no = {"Yes" : 1, "No" : 0}

In [45]:

for i in questionnaires:
    print(i, random.rand(yes_no))

TypeError: Random.random() takes no arguments (1 given)

In [ ]:
["Do you often find it hard to understand jokes, sarcasm, or figurative language?",
"Do you sometimes repeat words, phrases, or sentences in conversations (echolalia)?"
"Do you struggle to start or maintain a back-and-forth conversation?",
"Do you avoid making eye contact while speaking?",
"Do you find it difficult to judge when it’s your turn to speak in a conversation?",
"Do you often take what people say very literally?",
"Do you find it challenging to explain your thoughts or feelings in words?",
"Do people often tell you that your tone of voice sounds unusual or “flat”?",
"Do you struggle to adjust your way of speaking depending on who you are talking to (e.g., child vs. adult)?",
"Do you often speak at length about your favorite topic, even if the other person isn’t interested?"
]